name: nohunger
description: "A Multivendor App."
version: 1.0.4+4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  form_field_validator: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html_core: ^0.16.0
  animations: ^2.0.11
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  flutter_animated_splash: ^0.0.10
  page_transition: ^2.2.1
  animated_splash_screen: ^1.3.0
  animated_toggle_switch: ^0.8.4
  font_awesome_flutter: ^10.8.0
  liquid_swipe: ^3.1.0
  shared_preferences: ^2.5.3
  fl_chart: ^0.71.0
  syncfusion_flutter_charts: ^29.1.40


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#5203D5"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png
    - assets/logo/new/logo-nohunger-purple.png
    - assets/logo/new/
    - assets/images/user/
    - assets/images/stores/
    - assets/images/user/svg/
   
    - assets/images/user/stocks/other/
    - assets/images/user/stocks/raw/
    - assets/images/user/stocks/
    - assets/icons/
    - assets/icons/user/
    - assets/illustrations/
    - assets/flags/
    - assets/logo/
    - assets/screenshots/

  fonts:
    - family: Plus Jakarta
      fonts:
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Regular.otf
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Bold.otf
          weight: 700
    - family: Grandis Extended
      fonts:
        - asset: assets/fonts/grandis_extended/GrandisExtended-Regular.ttf
        - asset: assets/fonts/grandis_extended/GrandisExtended-Thin.ttf
          weight: 300
        - asset: assets/fonts/grandis_extended/GrandisExtended-Medium.ttf
          weight: 500
        - asset: assets/fonts/grandis_extended/GrandisExtended-Bold.ttf
          weight: 700
        - asset: assets/fonts/grandis_extended/GrandisExtended-Black.ttf
          weight: 900